/** Exact spoken scripts, shared by the floating reader and trainer PDF. */
export interface SpeakerNote {
  script: string[];
}

export const speakerNotes: Record<string, SpeakerNote> = {
  overview: {
    script: [
      "Welcome, everyone. Today we are practising how to help a newcomer to the Method feel welcome, understood and ready for their first Studio Session.",
      "We will explore the induction conversation, use member records to ask better questions, and practise with different situations and personalities.",
      "The goal is a clear, personal conversation that helps the community member feel more confident than they did when they arrived.",
      "By the end, I would like each of you to choose one thing you will do differently in your next induction.",
      "Let’s begin with why the induction matters.",
    ],
  },
  m1: {
    script: [
      "Think about someone walking into Physique 57 for their first Studio Session. What do they not know that we take for granted?",
      "Where to go, what to bring, what the session will feel like, and who to ask for help may all be unfamiliar.",
      "What else would you add to that list?",
      "Now imagine being the only person in the room who does not know those things. How might that feel?",
      "An induction helps remove that uncertainty. It gives the member a person to turn to and a clear next step.",
      "Here is the part worth sitting with: nobody complains about a missing induction. They simply stop coming, and we find out weeks later when the package goes unused.",
      "Without one, a member guesses \u2014 wrong class, wrong level, wrong expectation \u2014 and then reads a bad first session as \u2018this is not for me\u2019 rather than \u2018I picked the wrong class\u2019.",
      "They also never find a person. With no one name they trust, a reschedule or a niggling injury becomes a reason to skip instead of a reason to ask.",
      "And we learn nothing. No goal, no history, no constraint recorded, so every later conversation starts from zero.",
      "Now the other side. This is fifteen minutes that shapes the next twelve months, and it is the cheapest and most controllable moment we have.",
      "We cannot control the member\u2019s week or how the class lands. We can control whether they leave their first visit with a clear next step and one person who knows them.",
      "Remember that by the time they reach us, they have already said yes. Nothing here is persuasion. It is the handover, and it is their first evidence that the yes was a good decision.",
      "What is one small thing you could do to make that first visit feel easier?",
      "If that is the problem we are solving, how should a member feel after the conversation?",
    ],
  },
  m2: {
    script: [
      "On your own, write down how a community member should feel after their first induction with us. One word or one short line for each feeling.",
      "Think about the member’s experience rather than the information you would cover.",
      "What did you write? Let’s hear the different answers around the room.",
      "If the member knows where the changing rooms are, what feeling does that give them? If they know whom to ask for help, what changes for them?",
      "We want the member to feel welcomed, understood, informed, confident, comfortable and connected.",
      "We measure a successful induction by what the member understands and how supported they feel.",
      "Let’s look at the conversation that helps us get there.",
    ],
  },
  m3: {
    script: [
      "Seven steps, one conversation: welcome, discover, decode, navigate, tour, personalise and close.",
      "First, welcome the member by name and introduce yourself. Then discover what brought them to the Method and what matters to them.",
      "Decode the Signature Experiences in language they can understand. Navigate the booking essentials and explain the policies accurately.",
      "Show them around the Studio Space. Personalise the options using what they have actually shared, then agree a next step.",
      "Who would like to be our community member for a practice conversation? Everyone else, notice the questions that help us learn something useful.",
      "Which questions opened the conversation? Which statements helped the member feel more confident?",
      "The CRM gives us a starting point. Let’s practise turning that information into questions.",
    ],
  },
  m4: {
    script: [
      "Look at Brooke’s profile. What does the record tell us, and what do we still need to ask?",
      "Her goal mentions a wedding in July 2026. A date on file may no longer be current, so we need to check whether that goal still matters to her.",
      "What would you ask to understand what meaningful progress looks like for Brooke?",
      "One opening is: ‘What would meaningful progress look like for you personally?’ A follow-up is: ‘What would that change in how you feel or what you can do?’",
      "Zero recorded visits tells us about attendance. It does not tell us her fitness level or whether she feels nervous.",
      "Sensitive information calls for discretion. We can ask: ‘Is there anything you would like to discuss privately with your Instructor before the session?’ We do not diagnose or promise that a session is medically safe.",
      "Let’s compare your questions and inferences with the examples. An inference is a possibility to explore, and the member’s answer may change it.",
      "Remember the six verbs: see, infer, ask, listen, connect and act. Notice a fact, ask for context, then use the answer to help.",
      "Now let’s practise asking one level deeper before recommending anything.",
    ],
  },
  m5: {
    script: [
      "A member says, ‘I want to tone.’ What would you ask before suggesting a Signature Experience?",
      "‘What does feeling toned mean to you?’ gives the member room to explain the goal in their own words.",
      "If they say, ‘Evenings are easier,’ we can ask, ‘Which evenings fit most comfortably into your week?’",
      "Now look at the statement on screen. Give us one useful follow-up question and explain what you think might be worth exploring.",
      "Keep your inference tentative. The same statement can have several explanations.",
      "For this exercise, stay with discovery. Ask one open question, then listen before choosing a follow-up.",
      "‘Have you tried Barre?’ steers towards a solution. ‘What would make this worthwhile for you?’ helps us understand the person.",
      "Let’s expand the example and compare. What makes that question useful, and what might the member’s answer change?",
      "Once we understand the need, we can explain the relevant options clearly.",
    ],
  },
  m6: {
    script: [
      "We will work through the three transformations \u2014 policies, formats and recommendations \u2014 using the rules members actually ask about.",
      "For each policy you will see the robotic version and the human version of the same rule, with the reason underneath.",
      "The reason is the part that matters. Doors close so that nobody misses a safe set-up. Cancellation windows exist so somebody on the waitlist can take the place. Grip socks are a safety item, not an upsell.",
      "Notice that the human version never apologises for the rule and never threatens with it. It simply tells the member what they need in order to have a good experience.",
      "The full reference \u2014 refunds, freezes, transfers, what runs at which studio, and the claims we are allowed to make \u2014 sits in the Policies and Facts Pack in the toolkit.",
      "Policies, formats and recommendations are three places where a helpful conversation can become a long speech.",
      "Explain the booking rules clearly and accurately, with enough context for the member to use them.",
      "What difference do you hear between ‘Our policy states…’ and ‘One important thing to remember when you are booking…’?",
      "For Signature Experiences, explain the difference that matters to this member. Connect it to what they have told you.",
      "A useful recommendation sounds like: ‘Based on what you have told me, I think you may enjoy this option. How does that sound to you?’",
      "The member keeps a choice. If you are unsure about a policy or a detail, check it before giving an answer.",
      "How would you explain a booking policy in a way that is warm, clear and complete?",
      "We have explored good practice. Let’s see what happens when the conversation goes wrong.",
    ],
  },
  m7: {
    script: [
      "For this practice round, we need one associate and one community member. Everyone else will observe the servicing behaviours on screen.",
      "Associate, your challenge is to demonstrate the poor behaviours on the list. Observers, call out each behaviour you notice.",
      "We are discussing behaviours, so please keep real colleagues and real member details out of the example.",
      "What did the associate do that made the conversation harder for the member?",
      "What would you change first, and how would that help?",
      "These moments can be funny in a practice round, but they can make a real member feel overlooked or overwhelmed.",
      "Let’s put the better approach into practice.",
    ],
  },
  m8: {
    script: [
      "We will practise a full induction with an associate, a community member and an observer.",
      "Associates, use the CRM profile as your starting point. Community members, keep your role brief private and respond as the person described.",
      "Observers, focus on connect, curious, clear, complete and continue. Give feedback on the conversation and what the member understood.",
      "Start with a welcome, discover what matters to the member, and work towards a clear next step.",
      "What did the associate learn by asking? Which part of the conversation helped the member most?",
      "Now swap roles so everyone has the chance to experience the conversation from the member’s side.",
      "Real conversations have interruptions. Let’s practise keeping the thread when that happens.",
    ],
  },
  m9: {
    script: [
      "One person will begin an induction. Our observer will introduce a member question or Studio Space interruption during the conversation.",
      "Respond to what is happening, then help the member return to the conversation and their next step.",
      "If you do not know an answer, say: ‘That is a useful question. Let me check the information and come back to you.’",
      "Which point in the conversation did you return to after the interruption? What helped you keep the member supported?",
      "Let’s try another situation, then give someone else a turn as the associate.",
      "We can stay calm, be honest about what we know, and keep the member’s needs in view.",
      "Our final exercise checks what the member actually remembers.",
    ],
  },
  m10: {
    script: [
      "We will practise one final induction. Afterwards, I will ask the community member: ‘What do you remember?’",
      "Associate, what information do you remember sharing?",
      "Let’s compare those answers. What stayed with the member, and what did not?",
      "What could make the important information easier to understand and remember?",
      "Our job is to help the member leave with confidence, useful information and a clear next step.",
      "There is one more habit that makes this useful for the whole team: recording what we learned.",
    ],
  },
  studio: {
    script: [
      "The Member Studio has selected a random community member profile for this round. Look at what is recorded and notice what remains unknown.",
      "Write two questions you would actually ask, then describe one possible inference and the recorded facts that support it.",
      "What open question would let the member confirm, correct or explain that inference?",
      "After you have written your response, compare it with the review checklist and question coach.",
      "Which of your questions would you open with? What would you listen for before asking the next one?",
      "For group role-play, we can use the associate, community member and observer roles to practise the full conversation.",
      "Keep the practice notes separate from confirmed member feedback. We only record member statements in the CRM when they have actually shared them.",
    ],
  },
  members: {
    script: [
      "Here is your randomly selected member profile. Read it as a starting point for a conversation.",
      "What would you ask this member, and which recorded detail makes that question useful?",
      "Write your opening question and a second question that goes deeper. You can add a follow-up as well.",
      "Now describe one possible inference, the evidence behind it, and the question you would use to check it.",
      "An attendance pattern does not establish motivation. A blank field does not tell us what the member thinks or feels.",
      "Let’s review your response. Are the questions open, personal and neutral? Could the member comfortably correct your interpretation?",
      "When we are ready, we can try a different random profile and practise again.",
    ],
  },
  loop: {
    script: [
      "Before the conversation, the CRM gives us a head start. During the conversation, we learn what the record cannot tell us. Afterwards, we capture what the member actually shared.",
      "Write ‘Community member reported…’ or ‘Member requested…’ and use their exact words where helpful.",
      "Keep objective observations separate from the member’s stated concern. An inference stays unconfirmed until we check it.",
      "Record the action offered, the member’s response, who owns the follow-up and when it is due.",
      "The next associate should be able to understand what happened and continue the conversation without asking the member to start again.",
      "Let’s make updating the record part of the same-day follow-up.",
    ],
  },
  policy: {
    script: [
      "This section is the reference pack: the standing rules a member is most likely to ask you about during an induction.",
      "You are not expected to recite it. You are expected to know where the line is, so your conversation can stay warm and accurate at the same time.",
      "Start with the first visit. Fifteen minutes early, grip socks, waiver signed before entering any class \u2014 and the first experience differs by city, so check which one applies before you offer it.",
      "The doors are the rule we never bend. Barre and Strength Lab lock at plus ten minutes, powerCycle at plus five. Say it once at the induction, warmly, with the reason: a late entry costs a safe set-up and costs the room its focus.",
      "Cancellation is twelve hours for classes and twenty-four hours in writing for privates. Say it at the start of the relationship, not in the middle of a dispute.",
      "Freeze requests go to the city email at least forty-eight hours ahead, and they extend validity one for one. Rollover is once per member, on approval \u2014 goodwill, never a promise at the point of sale.",
      "Refunds: everything is strictly non-refundable, and a timely cancellation returns credit to the account. If a member quotes you a price you do not recognise, never match it on the spot \u2014 confirm, then come back.",
      "Then the level ladder. Barre first, four classes before the extensions, and the Strength Lab on-ramp of the four-Barre base plus screening and onboarding. The ladder protects the member; short-circuiting it is the commonest cause of first-month dropout.",
      "Know what runs where. Bengaluru has no powerCycle and no Strength Lab \u2014 offer FIT, HIIT and Back Body Blaze as the strength path rather than a promise we cannot keep.",
      "On results, we are confident about the method and honest about the individual. Over eighty percent see visible results in as few as eight classes, four sessions a week to see real change, and results vary with attendance, sleep and starting point.",
      "Health disclosures are captured at the waiver, tagged, and briefed to the Instructor before every session \u2014 and seen only by the Instructor and the Team Leader. We describe, modify and refer. We never diagnose.",
      "Last, the words. Investment rather than cost, preferred rate rather than discount, introductory experience rather than trial class. And never the word Spinning \u2014 it is somebody else\u2019s trademark.",
      "The one rule behind every line here: state it once, warmly, with the reason attached, then move to what we can do.",
    ],
  },
  cheat: {
    script: [
      "This is our quick reference for the induction conversation: welcome, discover, decode, navigate, tour, personalise and close.",
      "Use it to remember the essentials while keeping your words natural and relevant to the member.",
      "Ask one level deeper, explain what matters, check understanding and agree a next step.",
      "A useful reference supports the conversation. The member’s answers still guide it.",
    ],
  },
  never: {
    script: [
      "There are some behaviours we leave out of every induction.",
      "We do not overwhelm members with information, recite their whole profile, or make assumptions about their goals or feelings.",
      "We do not discuss sensitive health information publicly, diagnose, or promise that a Studio Session is medically safe.",
      "We do not invent policy answers or promise a transformation we cannot guarantee.",
      "We listen before recommending, explain accurately, and respect the member’s choices.",
      "Personalisation should help the member feel understood and supported.",
    ],
  },
  close: {
    script: [
      "From today, let’s think of induction as our first proper servicing conversation after someone chooses to join the P57 Community.",
      "The CRM gives us a head start, but it does not give us the person. That is what the conversation is for.",
      "Be curious. Ask better questions. Listen properly. Make the information relevant and help the member feel more confident in the Studio Space.",
      "Before we finish, what is one thing you will do differently in your very next induction?",
      "Let’s hear one commitment from each of you.",
      "Show community members how well we understand them through the care we take, the questions we ask and the follow-through we provide.",
      "Thank you, everyone. Let’s carry that into the next member conversation.",
    ],
  },
};
